-- =========================================================
-- setup_all.sql
-- CDTI Smart Lost & Found — Phase 1 full setup
-- Auto-generated by concatenating supabase/migrations/*.sql in order.
-- Run this once against a fresh Supabase project (SQL Editor or
-- `supabase db push` / `psql -f setup_all.sql`).
-- =========================================================

-- ---------- migrations/0001_enums.sql ----------
-- =========================================================
-- 0001_enums.sql
-- CDTI Smart Lost & Found — Phase 1: Enum types
-- =========================================================

create type public.user_type_enum as enum (
  'vocational_student',
  'university_student',
  'teacher_staff',
  'royal_household_staff',
  'external_visitor'
);

create type public.system_role_enum as enum (
  'user',
  'staff',
  'admin'
);

create type public.lost_item_status_enum as enum (
  'reported',
  'matched',
  'claim_pending',
  'returned',
  'closed',
  'cancelled'
);

create type public.found_item_status_enum as enum (
  'reported',
  'in_custody',
  'matched',
  'claim_pending',
  'verified',
  'returned',
  'closed'
);

create type public.custody_status_enum as enum (
  'with_finder',
  'transferred_to_staff',
  'in_storage',
  'released_to_owner'
);

create type public.claim_status_enum as enum (
  'pending',
  'insufficient',
  'needs_review',
  'likely_owner',
  'verified',
  'approved',
  'rejected',
  'disputed',
  'cancelled'
);

create type public.verification_level_enum as enum (
  'standard',
  'enhanced'
);

create type public.risk_level_enum as enum (
  'low',
  'medium',
  'high'
);

-- ---------- migrations/0002_profiles.sql ----------
-- =========================================================
-- 0002_profiles.sql
-- profiles table (1:1 with auth.users) + role helper functions
-- =========================================================

create table public.profiles (
  id                    uuid primary key references auth.users(id) on delete cascade,
  email                 text not null,
  full_name             text not null,
  user_type             public.user_type_enum not null,
  role                  public.system_role_enum not null default 'user',
  must_change_password  boolean not null default false,
  phone                 text,
  is_restricted         boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

comment on table public.profiles is
  'Extends auth.users. role is the ONLY source of truth for admin/staff authorization — never check email.';

-- ---------------------------------------------------------
-- Helper functions (SECURITY DEFINER so they can read
-- profiles.role without recursive RLS lookups)
-- ---------------------------------------------------------

create or replace function public.current_user_role()
returns public.system_role_enum
language sql
security definer
stable
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()) = 'admin', false);
$$;

create or replace function public.is_staff_or_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()) in ('staff','admin'), false);
$$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_staff_or_admin() to authenticated;

-- updated_at trigger helper (reused by every table)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------
-- RLS
-- ---------------------------------------------------------
alter table public.profiles enable row level security;

-- Users can see their own profile; staff/admin can see everyone.
create policy profiles_select_own_or_staff
  on public.profiles for select
  using (id = auth.uid() or public.is_staff_or_admin());

-- Users can update their own profile EXCEPT role / must_change_password,
-- which are protected by the trigger below.
create policy profiles_update_own
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- Admin can update anyone (role changes, restrictions, etc).
create policy profiles_update_admin
  on public.profiles for update
  using (public.is_admin())
  with check (true);

-- Profile row is created by a trigger on auth.users (see below), not by the client.
-- No insert policy for authenticated/anon -> default deny.

-- Prevent a non-admin from ever escalating their own role.
create or replace function public.prevent_self_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    if new.role is distinct from old.role then
      raise exception 'Only admins can change role';
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_profiles_block_self_role_escalation
  before update on public.profiles
  for each row execute function public.prevent_self_role_escalation();

-- ---------------------------------------------------------
-- Auto-create a profile row when a new auth.users row appears
-- ---------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, user_type, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    coalesce((new.raw_user_meta_data->>'user_type')::public.user_type_enum, 'external_visitor'),
    'user'
  );
  return new;
end;
$$;

create trigger trg_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- migrations/0003_reference_tables.sql ----------
-- =========================================================
-- 0003_reference_tables.sql
-- categories, locations, handover_locations
-- Public read, admin-only write.
-- =========================================================

create table public.categories (
  id          uuid primary key default gen_random_uuid(),
  name_th     text not null,
  name_en     text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.locations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  description text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.handover_locations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  address     text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.locations enable row level security;
alter table public.handover_locations enable row level security;

-- Anyone (including anon/guest browsing) can read active reference data.
create policy categories_select_all
  on public.categories for select using (true);
create policy locations_select_all
  on public.locations for select using (true);
create policy handover_locations_select_all
  on public.handover_locations for select using (true);

-- Only admin can write.
create policy categories_write_admin
  on public.categories for all
  using (public.is_admin()) with check (public.is_admin());
create policy locations_write_admin
  on public.locations for all
  using (public.is_admin()) with check (public.is_admin());
create policy handover_locations_write_admin
  on public.handover_locations for all
  using (public.is_admin()) with check (public.is_admin());

-- ---------- migrations/0004_lost_items.sql ----------
-- =========================================================
-- 0004_lost_items.sql
-- =========================================================

create table public.lost_items (
  id                       uuid primary key default gen_random_uuid(),
  reporter_id              uuid not null references public.profiles(id) on delete cascade,
  category_id              uuid references public.categories(id),
  item_name                text not null,
  brand                    text,
  color                    text,
  lost_date                date,
  location_id              uuid references public.locations(id),
  description              text,
  public_image_url         text,
  -- private / verification-only columns:
  private_ownership_details text,
  private_image_url        text,
  status                   public.lost_item_status_enum not null default 'reported',
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

comment on column public.lost_items.private_ownership_details is
  'NEVER exposed through public views/search. Used only for claim verification.';

create trigger trg_lost_items_updated_at
  before update on public.lost_items
  for each row execute function public.set_updated_at();

alter table public.lost_items enable row level security;

-- Owner (reporter) sees full row, including private columns.
create policy lost_items_select_owner
  on public.lost_items for select
  using (reporter_id = auth.uid());

-- Staff/admin see everything (needed for review, matching, disputes).
create policy lost_items_select_staff
  on public.lost_items for select
  using (public.is_staff_or_admin());

-- Only the reporter may create their own report.
create policy lost_items_insert_owner
  on public.lost_items for insert
  with check (reporter_id = auth.uid());

-- Reporter can edit their own report; staff/admin can edit any (status changes, review).
create policy lost_items_update_owner
  on public.lost_items for update
  using (reporter_id = auth.uid())
  with check (reporter_id = auth.uid());

create policy lost_items_update_staff
  on public.lost_items for update
  using (public.is_staff_or_admin())
  with check (public.is_staff_or_admin());

-- No public/anon SELECT policy on the base table at all.
-- Public/anon access happens only through public_lost_items (Phase 1 view, see 0018).

-- ---------- migrations/0005_found_items.sql ----------
-- =========================================================
-- 0005_found_items.sql
-- =========================================================

create table public.found_items (
  id                  uuid primary key default gen_random_uuid(),
  finder_id           uuid not null references public.profiles(id) on delete cascade,
  category_id         uuid references public.categories(id),
  general_name        text not null,
  color                text,
  found_date          date,
  location_id         uuid references public.locations(id),   -- general/public location
  description         text,
  public_image_url    text,
  -- private / verification-only columns:
  private_image_url   text,
  exact_location       text,
  exact_time           timestamptz,
  serial_number        text,
  secret_details        text,
  custody_status       public.custody_status_enum not null default 'with_finder',
  status               public.found_item_status_enum not null default 'reported',
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on column public.found_items.secret_details is
  'The core anti-fraud secret. NEVER exposed via API/notification/public view. Used only in claim verification checklist by staff/admin logic.';

create trigger trg_found_items_updated_at
  before update on public.found_items
  for each row execute function public.set_updated_at();

alter table public.found_items enable row level security;

-- Finder sees full row, including private/secret columns.
create policy found_items_select_finder
  on public.found_items for select
  using (finder_id = auth.uid());

-- Staff/admin see everything.
create policy found_items_select_staff
  on public.found_items for select
  using (public.is_staff_or_admin());

-- Only the finder may create their own found-item report.
create policy found_items_insert_finder
  on public.found_items for insert
  with check (finder_id = auth.uid());

-- Finder can edit their own report; staff/admin can edit any (custody transfer, status).
create policy found_items_update_finder
  on public.found_items for update
  using (finder_id = auth.uid())
  with check (finder_id = auth.uid());

create policy found_items_update_staff
  on public.found_items for update
  using (public.is_staff_or_admin())
  with check (public.is_staff_or_admin());

-- IMPORTANT: claimants must NEVER get a direct SELECT policy on this table —
-- that would leak secret_details. Claimants only see item data through
-- public_found_items (public columns) and through the claims flow, which
-- never returns secret_details to the client.

-- ---------- migrations/0006_matches.sql ----------
-- =========================================================
-- 0006_matches.sql
-- System-generated potential matches between lost_items and found_items.
-- =========================================================

create table public.matches (
  id             uuid primary key default gen_random_uuid(),
  lost_item_id   uuid not null references public.lost_items(id) on delete cascade,
  found_item_id  uuid not null references public.found_items(id) on delete cascade,
  score          numeric(5,2) not null check (score >= 0 and score <= 100),
  score_breakdown jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now(),
  unique (lost_item_id, found_item_id)
);

alter table public.matches enable row level security;

-- Only the two involved parties (lost reporter + found finder) and staff/admin
-- may see a match. This is a "potential match" notice, never proof of ownership.
create policy matches_select_involved_parties
  on public.matches for select
  using (
    public.is_staff_or_admin()
    or exists (select 1 from public.lost_items li where li.id = lost_item_id and li.reporter_id = auth.uid())
    or exists (select 1 from public.found_items fi where fi.id = found_item_id and fi.finder_id = auth.uid())
  );

-- No INSERT/UPDATE/DELETE policy for authenticated/anon: matches are written
-- exclusively by the backend matching job using the service role key,
-- which bypasses RLS entirely. This keeps scoring logic server-side only.

-- ---------- migrations/0007_claims.sql ----------
-- =========================================================
-- 0007_claims.sql
-- =========================================================

create table public.claims (
  id                   uuid primary key default gen_random_uuid(),
  claimant_id          uuid not null references public.profiles(id) on delete cascade,
  found_item_id        uuid not null references public.found_items(id) on delete cascade,
  match_id             uuid references public.matches(id),
  status               public.claim_status_enum not null default 'pending',
  verification_level   public.verification_level_enum not null default 'standard',
  answers              jsonb not null default '{}'::jsonb, -- questionnaire answers, private
  claim_attempt_count  integer not null default 0,
  last_attempt_at      timestamptz,
  reviewed_by          uuid references public.profiles(id),
  reviewed_at          timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on column public.claims.answers is
  'Claimant questionnaire answers used for ownership verification. Never contains password/PIN/credentials (enforced at application layer).';

create trigger trg_claims_updated_at
  before update on public.claims
  for each row execute function public.set_updated_at();

alter table public.claims enable row level security;

-- Claimant sees only their own claims.
create policy claims_select_claimant
  on public.claims for select
  using (claimant_id = auth.uid());

-- Staff/admin see all claims (review, dispute handling).
create policy claims_select_staff
  on public.claims for select
  using (public.is_staff_or_admin());

-- Only the claimant may open a claim, on their own behalf.
create policy claims_insert_claimant
  on public.claims for insert
  with check (claimant_id = auth.uid());

-- Claimant may update limited fields of their own pending claim (e.g. re-answer);
-- application layer / additional CHECK constraints should restrict which
-- columns are editable once status has left 'pending'.
create policy claims_update_claimant
  on public.claims for update
  using (claimant_id = auth.uid())
  with check (claimant_id = auth.uid());

-- Staff/admin can update any claim (approve/reject/needs_review/disputed).
create policy claims_update_staff
  on public.claims for update
  using (public.is_staff_or_admin())
  with check (public.is_staff_or_admin());

-- NOTE: the finder of the found_item deliberately has NO access to this table.
-- This preserves information asymmetry — the person who found the item must
-- never see who is claiming it or what they answered.

-- ---------- migrations/0008_claim_evidence.sql ----------
-- =========================================================
-- 0008_claim_evidence.sql
-- =========================================================

create table public.claim_evidence (
  id           uuid primary key default gen_random_uuid(),
  claim_id     uuid not null references public.claims(id) on delete cascade,
  evidence_url text not null,   -- points into the PRIVATE storage bucket
  description  text,
  created_at   timestamptz not null default now()
);

alter table public.claim_evidence enable row level security;

-- Visible only to: the claimant who owns the parent claim, and staff/admin.
-- Never to the finder, never to the public.
create policy claim_evidence_select_owner_or_staff
  on public.claim_evidence for select
  using (
    public.is_staff_or_admin()
    or exists (select 1 from public.claims c where c.id = claim_id and c.claimant_id = auth.uid())
  );

create policy claim_evidence_insert_owner
  on public.claim_evidence for insert
  with check (
    exists (select 1 from public.claims c where c.id = claim_id and c.claimant_id = auth.uid())
  );

-- Evidence is immutable once submitted: no UPDATE policy.
-- Only staff/admin may delete (e.g. moderation of inappropriate upload).
create policy claim_evidence_delete_staff
  on public.claim_evidence for delete
  using (public.is_staff_or_admin());

-- ---------- migrations/0009_notifications.sql ----------
-- =========================================================
-- 0009_notifications.sql
-- =========================================================

create table public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  type        text not null,          -- e.g. 'potential_match','claim_received','claim_approved', ...
  title       text not null,
  message     text not null,
  payload     jsonb not null default '{}'::jsonb,  -- MUST NOT contain secret_details, see app-layer rule
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);

alter table public.notifications enable row level security;

-- Users only ever see their own notifications.
create policy notifications_select_own
  on public.notifications for select
  using (user_id = auth.uid());

-- Users can mark their own notifications as read, nothing else.
create policy notifications_update_own_mark_read
  on public.notifications for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Staff/admin can read all notifications for support/debugging.
create policy notifications_select_staff
  on public.notifications for select
  using (public.is_staff_or_admin());

-- No INSERT policy for authenticated/anon: notifications are created
-- server-side (service role / triggers) only, so app logic controls
-- exactly what payload is exposed and secret_details can never leak this way.

-- ---------- migrations/0010_risk_events.sql ----------
-- =========================================================
-- 0010_risk_events.sql
-- =========================================================

create table public.risk_events (
  id                uuid primary key default gen_random_uuid(),
  event_type        text not null,   -- e.g. 'frequent_claims','repeated_rejections','duplicate_claim_target','answer_changed','new_account_high_value'
  risk_level        public.risk_level_enum not null default 'low',
  related_user_id   uuid references public.profiles(id),
  related_item_id   uuid,            -- may point to lost_items.id or found_items.id (app-level union, no FK to keep it generic)
  related_claim_id  uuid references public.claims(id),
  resolution        text,            -- neutral wording only, e.g. 'needs_review' — never "thief"/"scammer"
  resolved_by       uuid references public.profiles(id),
  resolved_at       timestamptz,
  created_at        timestamptz not null default now()
);

alter table public.risk_events enable row level security;

-- Staff/admin only, full stop. Risk signals are never exposed to end users.
create policy risk_events_select_staff
  on public.risk_events for select
  using (public.is_staff_or_admin());

create policy risk_events_update_staff
  on public.risk_events for update
  using (public.is_staff_or_admin())
  with check (public.is_staff_or_admin());

-- No INSERT policy for authenticated/anon: risk events are raised by
-- server-side risk-detection logic (service role) only.

-- ---------- migrations/0011_audit_logs.sql ----------
-- =========================================================
-- 0011_audit_logs.sql
-- Append-only audit trail. Nobody — including admin — may UPDATE or DELETE.
-- =========================================================

create table public.audit_logs (
  id           uuid primary key default gen_random_uuid(),
  actor_id     uuid references public.profiles(id),  -- null allowed for system/service actions
  action       text not null,          -- e.g. 'item.created','claim.approved','handover.completed'
  entity_type  text not null,          -- e.g. 'lost_item','found_item','claim','handover_code'
  entity_id    uuid,
  metadata     jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

-- Staff/admin can read the audit trail.
create policy audit_logs_select_staff
  on public.audit_logs for select
  using (public.is_staff_or_admin());

-- No INSERT policy for authenticated/anon: audit rows are written exclusively
-- by server-side triggers/functions using the service role key.
-- No UPDATE or DELETE policy exists for ANY role — the table is immutable
-- by design (defense against tampering, even by a compromised admin session).

-- ---------- migrations/0012_custody_history.sql ----------
-- =========================================================
-- 0012_custody_history.sql
-- =========================================================

create table public.custody_history (
  id             uuid primary key default gen_random_uuid(),
  found_item_id  uuid not null references public.found_items(id) on delete cascade,
  from_status    public.custody_status_enum,
  to_status      public.custody_status_enum not null,
  handled_by     uuid references public.profiles(id),
  location_id    uuid references public.handover_locations(id),
  notes          text,
  created_at     timestamptz not null default now()
);

alter table public.custody_history enable row level security;

-- Staff/admin: full visibility (chain-of-custody audit).
create policy custody_history_select_staff
  on public.custody_history for select
  using (public.is_staff_or_admin());

-- The finder can see the custody trail of the item they reported, for transparency.
create policy custody_history_select_finder
  on public.custody_history for select
  using (
    exists (
      select 1 from public.found_items fi
      where fi.id = found_item_id and fi.finder_id = auth.uid()
    )
  );

-- No INSERT/UPDATE/DELETE policy for authenticated/anon: custody transitions
-- are recorded exclusively by server-side handover logic (service role),
-- keeping the chain of custody tamper-resistant from the client side.

-- ---------- migrations/0013_internal_notes.sql ----------
-- =========================================================
-- 0013_internal_notes.sql
-- Staff/admin-only internal notes attached to any entity
-- (found_item, lost_item, claim, risk_event, ...).
-- =========================================================

create table public.internal_notes (
  id           uuid primary key default gen_random_uuid(),
  entity_type  text not null,   -- 'lost_item' | 'found_item' | 'claim' | 'risk_event' | ...
  entity_id    uuid not null,
  author_id    uuid not null references public.profiles(id),
  note         text not null,
  created_at   timestamptz not null default now()
);

alter table public.internal_notes enable row level security;

-- Strictly staff/admin, both read and write. No end user ever sees this table.
create policy internal_notes_select_staff
  on public.internal_notes for select
  using (public.is_staff_or_admin());

create policy internal_notes_insert_staff
  on public.internal_notes for insert
  with check (public.is_staff_or_admin() and author_id = auth.uid());

create policy internal_notes_delete_staff
  on public.internal_notes for delete
  using (public.is_staff_or_admin());

-- ---------- migrations/0014_handover_codes.sql ----------
-- =========================================================
-- 0014_handover_codes.sql
-- One-time 6-digit codes used to confirm secure handover.
-- Only the HASH is stored; the plaintext code is shown to the
-- claimant exactly once (via notification/UI) at generation time.
-- =========================================================

create table public.handover_codes (
  id           uuid primary key default gen_random_uuid(),
  claim_id     uuid not null references public.claims(id) on delete cascade,
  code_hash    text not null,
  expires_at   timestamptz not null,
  used_at      timestamptz,
  used_by      uuid references public.profiles(id),
  created_at   timestamptz not null default now(),
  unique (claim_id)
);

alter table public.handover_codes enable row level security;

-- Staff/admin only: they are the ones who key in / verify the code at handover.
create policy handover_codes_select_staff
  on public.handover_codes for select
  using (public.is_staff_or_admin());

create policy handover_codes_update_staff
  on public.handover_codes for update
  using (public.is_staff_or_admin())
  with check (public.is_staff_or_admin());

-- No INSERT policy for authenticated/anon: codes are generated server-side
-- (service role) so the hash and plaintext are never both handled by the
-- client at once.

-- ---------- migrations/0015_public_views.sql ----------
-- =========================================================
-- 0015_public_views.sql
-- Public-safe views. These are the ONLY way anon/public users
-- browse listings — the base tables (lost_items/found_items)
-- have no public SELECT policy at all.
--
-- security_invoker = off (default for views) means the view runs
-- with the privileges of its owner, not the querying role — so it
-- can read the underlying table regardless of the caller's RLS
-- visibility, while only ever exposing the columns listed below.
-- =========================================================

create view public.public_lost_items
with (security_invoker = false) as
select
  li.id,
  li.category_id,
  c.name_th  as category_name_th,
  c.name_en  as category_name_en,
  li.item_name,
  li.color,
  li.lost_date,
  li.location_id,
  l.name     as location_name,
  li.description,
  li.public_image_url,
  li.status,
  li.created_at
from public.lost_items li
left join public.categories c on c.id = li.category_id
left join public.locations l on l.id = li.location_id
where li.status in ('reported', 'matched');
-- Explicitly EXCLUDED: reporter_id, private_ownership_details, private_image_url, updated_at

create view public.public_found_items
with (security_invoker = false) as
select
  fi.id,
  fi.category_id,
  c.name_th  as category_name_th,
  c.name_en  as category_name_en,
  fi.general_name,
  fi.color,
  fi.found_date,
  fi.location_id,
  l.name     as location_name,
  fi.description,
  fi.public_image_url,
  fi.status,
  fi.created_at
from public.found_items fi
left join public.categories c on c.id = fi.category_id
left join public.locations l on l.id = fi.location_id
where fi.status in ('reported', 'in_custody', 'matched');
-- Explicitly EXCLUDED: finder_id, private_image_url, exact_location, exact_time,
-- serial_number, secret_details, custody_status, updated_at

grant select on public.public_lost_items to anon, authenticated;
grant select on public.public_found_items to anon, authenticated;

comment on view public.public_lost_items is
  'Public/guest-safe listing. No reporter identity or private ownership details.';
comment on view public.public_found_items is
  'Public/guest-safe listing. No finder identity, secret_details, serial_number, or exact location/time.';

-- ---------- migrations/0016_storage_buckets.sql ----------
-- =========================================================
-- 0016_storage_buckets.sql
-- Two storage buckets:
--   item-images-public   -> public=true  (lost/found public photos)
--   verification-private -> public=false (claim evidence, private item photos)
-- =========================================================

insert into storage.buckets (id, name, public)
values ('item-images-public', 'item-images-public', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('verification-private', 'verification-private', false)
on conflict (id) do nothing;

-- ---------------------------------------------------------
-- item-images-public: anyone can view; only authenticated
-- users can upload, and only into a folder matching their own
-- user id (prefix convention: <auth.uid()>/filename.ext)
-- ---------------------------------------------------------
create policy storage_public_images_select
  on storage.objects for select
  using (bucket_id = 'item-images-public');

create policy storage_public_images_insert_own_folder
  on storage.objects for insert
  with check (
    bucket_id = 'item-images-public'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy storage_public_images_delete_own_or_staff
  on storage.objects for delete
  using (
    bucket_id = 'item-images-public'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_staff_or_admin())
  );

-- ---------------------------------------------------------
-- verification-private: NEVER publicly readable. Only the
-- uploader (own folder) and staff/admin may read; only the
-- uploader may insert into their own folder.
-- ---------------------------------------------------------
create policy storage_private_evidence_select_own_or_staff
  on storage.objects for select
  using (
    bucket_id = 'verification-private'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_staff_or_admin())
  );

create policy storage_private_evidence_insert_own_folder
  on storage.objects for insert
  with check (
    bucket_id = 'verification-private'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy storage_private_evidence_delete_staff
  on storage.objects for delete
  using (
    bucket_id = 'verification-private'
    and public.is_staff_or_admin()
  );

